[[experience]]
== Experience

=== National Capital FreeNet
*Ottawa, ON* +
*May 2026 - Present*

==== HelpDesk Analyst

* Configured assets such as modems
* Analyzed DSL and Fibre connections through Line Profiles and Active Sessions
* Troubleshoot issues regarding internet issues and other things like Email client issues, Windows and Apple connectivity, etc.

=== Agriculture and Agri-Food Canada (AAFC-AAC) - Government of Canada
*Ottawa, ON* +
*January 2024 - August 2025*

==== Programmer/Developer

Worked on the DINA project – a FOSS project / web application collaborated on by multiple government
departments such as AAFC, DFO, and Health Canada – React frontend, Postgres database, Java backend
* Used Python and ORM concepts and methodologies to migrate data from a legacy web application to a
newer application which improved data-entry efficiency by 100%
* Developed Python migration scripts based on data given by other departments to migrate Excel sheet data
into the DINA web application
* Updated Helm chart to fix migration problems that was found in RabbitMQ
* Migrated 10+ Enzyme tests to React Testing Library tests (Frontend tests)
* Updated tickets to document and keep track of work item progress

==== IT Technician

* Provided Tier 1/2 IT support to clients in Ottawa, ensuring timely and effective resolution of assigned tickets
* Managed user accounts in Active Directory
* Conducted desktop imaging and computer reimaging to streamline device deployment for end-users
* Diagnosed and resolved hardware issues, including upgrading RAM, replacing faulty components, and preparing legacy desktops for surplus
* Gained experience in IT asset lifecycle management, hardware/software troubleshooting, and modern workplace technologies

=== Ottawa Public Health (OPH) - City of Ottawa
*Ottawa, ON* +
*October 2020 - March 2024*

==== Data Entry and Verification Clerk
*Immunization Clinics*

* Used various database software for data entry such as Salesforce (COVax & CCM) and Panorama
* Ensured information shared by clients remain confidential and known only by the Ministry of Health and nurses

==== Data Entry and Verification Clerk Lead
*Mobile Clinics*

* Assessed client information for vaccination eligibility based on provincial and organizational directives in multiple Long Term Care and Retirement Home Clinics
* Trained clerks in implementing changes in Salesforce database software to help in clinical operations

==== Receptionist
*Immunization and Mobile Clinics*

* Managed flow of clients in clinics to ensure proper social distancing
* Guided clients and made sure customers had a comfortable experience in clinic

=== Personal Tutor
*January 2019 - Present*

* Taught Primary and Secondary School Level Mathematics i.e. topics ranging from basic arithmetic to high school level Calculus
* Talked to clients in a professional and friendly manner to provide a comfortable learning environment

=== Bio-Test Laboraotry Inc.
*Ottawa, ON* +
*October 2021 - November 2021*

==== Data Entry Clerk

* Managed and entered hundreds of client data in Schuylab Database Software
* Handled containers containing specimen with care to avoid workplace contamination
* Coordinated with a team on a daily basis to ensure completion of tasks in office
