== Experience

=== Agriculture and Agri-Food Canada (AAFC-AAC) - Government of Canada
*Ottawa, ON* +
*January 2024 - Present*

==== Programmer Analyst

* Learned programming best practices
* Worked in a team of programmers, managers, and other experts to build an open-source web application
* Learned and utilized various programming languages, scripting languages, and concepts to build and document projects

==== IT Technician

* Recycled old computers by removing old hard drives and clearing them and setting them up for delivery
* Talked to clients in a professional and friendly manner in order to solve problems
* Troubleshooting hardware and software problems

=== Ottawa Public Health (OPH) - City of Ottawa
*Ottawa, ON* +
*October 2020 - March 2024*

==== Data Entry and Verification Clerk
*Immunization Clinics*

* Used various database software for data entry such as Salesforce (COVax & CCM) and Panorama
* Ensured information shared by clients remain confidential and known only by the Ministry of Health and nurses

==== Data Entry and Verification Clerk Lead
*Mobile Clinics*

* Assessed client information for vaccination eligibility based on provincial and organizational directives in multiple Long Term Care and Retirement Home Clinics
* Trained clerks in implementing changes in Salesforce database software to help in clinical operations

==== Receptionist
*Immunization and Mobile Clinics*

* Managed flow of clients in clinics to ensure proper social distancing
* Guided clients and made sure customers had a comfortable experience in clinic

=== Personal Tutor
*January 2019 - Present*

* Taught Primary and Secondary School Level Mathematics i.e. topics ranging from basic arithmetic to high school level Calculus
* Talked to clients in a professional and friendly manner to provide a comfortable learning environment

=== Bio-Test Laboraotry Inc.
*Ottawa, ON* +
*October 2021 - November 2021*

==== Data Entry Clerk

* Managed and entered hundreds of client data in Schuylab Database Software
* Handled containers containing specimen with care to avoid workplace contamination
* Coordinated with a team on a daily basis to ensure completion of tasks in office
