name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Run generate Resume
        run: asciidoctor -a toc=preamble -D generated-docs asciiDoc/index.adoc

      - name: Copy files for resume pdf
        run: |
          mkdir generated-docs/files
          cp -r asciiDoc/files/. generated-docs/files

      - name: Deploy GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: generated-docs
