name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
    steps:
      - uses: actions/checkout@v4

      - name: Install asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Run generate Resume
        run: asciidoctor -a toc=preamble -D generated-docs asciiDoc/index.adoc

      - name: Copy files for resume pdf
        run: |
          mkdir generated-docs/files
          cp -r asciiDoc/files/. generated-docs/files

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'generated-docs'

      - name: Deploy GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
